name:                hsy

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Weverything
- -Werror
- -Wno-prepositive-qualified-module
- -Wno-implicit-prelude
- -Wno-missing-safe-haskell-mode
- -Wno-safe
- -Wno-unsafe
- -Wno-missing-deriving-strategies
- -Wno-missed-specialisations

library:
  source-dirs: src
  c-sources:
    - src/hydrogen.c
    - src/wrappers.c
  dependencies:
    - bytestring
    - text


executables:
  hsy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsy

tests:
  hsydrogen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsydrogen
